
$WWW_DIR/log/access.log \
$WWW_DIR/log/access_php-fpm.log \
$WWW_DIR/log/error.log \
$WWW_DIR/log/slow_php-fpm.log \
$WWW_DIR/log/error_php-fpm.log {
    weekly
    rotate 8
    missingok
    notifempty
    compress
    delaycompress
    dateext
    create 0640 $NEW_USER $HOSTING_GROUP
    sharedscripts
 	prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi \
        endscript
        postrotate
                invoke-rc.d nginx rotate >/dev/null 2>&1
		systemctl reload php$PHP_VERSION-fpm >/dev/null 2>&1 || true
        endscript
}
