#
# The default server
#

server {
    server_name $NEW_DOMAIN;
    server_tokens off;

    listen 80;
    listen [::]:80;
    http2 on;


    access_log /home/$NEW_USER/log/access.log;
    error_log /home/$NEW_USER/log/error.log;


    # include ssl-common.conf;
    # include listen-443.conf;
    # include wp-sitemaps.conf;
    # include gzip-common.conf;
    # include cache-common.conf;

    root /home/$NEW_USER/web;

    index index.php index.html;

    location /favicon.ico {
        log_not_found off;
        access_log off;
    }

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass unix:/var/run/php/$NEW_USER.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }


    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny all;
    }
}
